version: "3"
services:
   frontend:
       container_name: web-client
       build:
           context: ./client
           target: dev
           dockerfile: Dockerfile
       ports:
           - "3000:3000"
       volumes:
           - ./client:/app
   backend:
       container_name: web-server
       build:
           context: ./server
           dockerfile: Dockerfile
       ports:
           - "5000:5000"
       volumes:
           - ./server:/app/server