version: "3"
services:
   frontend:
       container_name: web-client
       build:
           context: ./client
           target: production
           dockerfile: Dockerfile
       ports:
           - "3000:3000"
       volumes:
           - ./client:/app/client
           - /app/client/node_modules
           - /app/client/.next
   backend:
       container_name: web-server
       build:
           context: ./server
           dockerfile: Dockerfile
       ports:
           - "5000:5000"
       volumes:
           - ./server:/app/server